name: manual run

on:
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/only-svg/github-contribution-grid-snake.svg?color_snake=#5D3FD3&speed=50
            dist/only-svg/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#5D3FD3&speed=50
            dist/only-svg/github-contribution-grid-snake-blue.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/docker/github-contribution-grid-snake.svg?color_snake=#5D3FD3&speed=50
            dist/docker/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#5D3FD3&speed=50
            dist/docker/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/only-svg/github-contribution-grid-snake.svg
          test -f dist/only-svg/github-contribution-grid-snake-dark.svg
          test -f dist/only-svg/github-contribution-grid-snake-blue.svg

          test -f dist/docker/github-contribution-grid-snake.svg
          test -f dist/docker/github-contribution-grid-snake-dark.svg
          test -f dist/docker/github-contribution-grid-snake.gif

      - name: Push to manual-run-output
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: manual-run-output
          folder: dist
          clean: true
          single-commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
          